package utils;

public class IsoSearch {
    private final static String[][] iso639Data = {
        {"Abkhazian","ab"},
        {"Afar","aa"},
        {"Afrikaans","af"},
        {"Akan","ak"},
        {"Albanian","sq"},
        {"Amharic","am"},
        {"Arabic","ar"},
        {"Aragonese","an"},
        {"Armenian","hy"},
        {"Assamese","as"},
        {"Avaric","av"},
        {"Avestan","ae"},
        {"Aymara","ay"},
        {"Azerbaijani","az"},
        {"Bambara","bm"},
        {"Bashkir","ba"},
        {"Basque","eu"},
        {"Belarusian","be"},
        {"Bengali","bn"},
        {"Bislama","bi"},
        {"Bosnian","bs"},
        {"Breton","br"},
        {"Bulgarian","bg"},
        {"Burmese","my"},
        {"Catalan, Valencian","ca"},
        {"Chamorro","ch"},
        {"Chechen","ce"},
        {"Chichewa, Chewa, Nyanja","ny"},
        {"Chinese","zh"},
        {"Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic","cu"},
        {"Chuvash","cv"},
        {"Cornish","kw"},
        {"Corsican","co"},
        {"Cree","cr"},
        {"Croatian","hr"},
        {"Czech","cs"},
        {"Danish","da"},
        {"Divehi, Dhivehi, Maldivian","dv"},
        {"Dutch, Flemish","nl"},
        {"Dzongkha","dz"},
        {"English","en"},
        {"Esperanto","eo"},
        {"Estonian","et"},
        {"Ewe","ee"},
        {"Faroese","fo"},
        {"Fijian","fj"},
        {"Finnish","fi"},
        {"French","fr"},
        {"Western Frisian","fy"},
        {"Fulah","ff"},
        {"Gaelic, Scottish Gaelic","gd"},
        {"Galician","gl"},
        {"Ganda","lg"},
        {"Georgian","ka"},
        {"German","de"},
        {"Greek, Modern (1453–)","el"},
        {"Kalaallisut, Greenlandic","kl"},
        {"Guarani","gn"},
        {"Gujarati","gu"},
        {"Haitian, Haitian Creole","ht"},
        {"Hausa","ha"},
        {"Hebrew","he"},
        {"Herero","hz"},
        {"Hindi","hi"},
        {"Hiri Motu","ho"},
        {"Hungarian","hu"},
        {"Icelandic","is"},
        {"Ido","io"},
        {"Igbo","ig"},
        {"Indonesian","id"},
        {"Interlingua (International Auxiliary Language Association)","ia"},
        {"Interlingue, Occidental","ie"},
        {"Inuktitut","iu"},
        {"Inupiaq","ik"},
        {"Irish","ga"},
        {"Italian","it"},
        {"Japanese","ja"},
        {"Javanese","jv"},
        {"Kannada","kn"},
        {"Kanuri","kr"},
        {"Kashmiri","ks"},
        {"Kazakh","kk"},
        {"Central Khmer","km"},
        {"Kikuyu, Gikuyu","ki"},
        {"Kinyarwanda","rw"},
        {"Kirghiz, Kyrgyz","ky"},
        {"Komi","kv"},
        {"Kongo","kg"},
        {"Korean","ko"},
        {"Kuanyama, Kwanyama","kj"},
        {"Kurdish","ku"},
        {"Lao","lo"},
        {"Latin","la"},
        {"Latvian","lv"},
        {"Limburgan, Limburger, Limburgish","li"},
        {"Lingala","ln"},
        {"Lithuanian","lt"},
        {"Luba-Katanga","lu"},
        {"Luxembourgish, Letzeburgesch","lb"},
        {"Macedonian","mk"},
        {"Malagasy","mg"},
        {"Malay","ms"},
        {"Malayalam","ml"},
        {"Maltese","mt"},
        {"Manx","gv"},
        {"Maori","mi"},
        {"Marathi","mr"},
        {"Marshallese","mh"},
        {"Mongolian","mn"},
        {"Nauru","na"},
        {"Navajo, Navaho","nv"},
        {"North Ndebele","nd"},
        {"South Ndebele","nr"},
        {"Ndonga","ng"},
        {"Nepali","ne"},
        {"Norwegian","no"},
        {"Norwegian Bokmål","nb"},
        {"Norwegian Nynorsk","nn"},
        {"Sichuan Yi, Nuosu","ii"},
        {"Occitan","oc"},
        {"Ojibwa","oj"},
        {"Oriya","or"},
        {"Oromo","om"},
        {"Ossetian, Ossetic","os"},
        {"Pali","pi"},
        {"Pashto, Pushto","ps"},
        {"Persian","fa"},
        {"Polish","pl"},
        {"Portuguese","pt"},
        {"Punjabi, Panjabi","pa"},
        {"Quechua","qu"},
        {"Romanian, Moldavian, Moldovan","ro"},
        {"Romansh","rm"},
        {"Rundi","rn"},
        {"Russian","ru"},
        {"Northern Sami","se"},
        {"Samoan","sm"},
        {"Sango","sg"},
        {"Sanskrit","sa"},
        {"Sardinian","sc"},
        {"Serbian","sr"},
        {"Shona","sn"},
        {"Sindhi","sd"},
        {"Sinhala, Sinhalese","si"},
        {"Slovak","sk"},
        {"Slovenian","sl"},
        {"Somali","so"},
        {"Southern Sotho","st"},
        {"Spanish, Castilian","es"},
        {"Sundanese","su"},
        {"Swahili","sw"},
        {"Swati","ss"},
        {"Swedish","sv"},
        {"Tagalog","tl"},
        {"Tahitian","ty"},
        {"Tajik","tg"},
        {"Tamil","ta"},
        {"Tatar","tt"},
        {"Telugu","te"},
        {"Thai","th"},
        {"Tibetan","bo"},
        {"Tigrinya","ti"},
        {"Tonga (Tonga Islands)","to"},
        {"Tsonga","ts"},
        {"Tswana","tn"},
        {"Turkish","tr"},
        {"Turkmen","tk"},
        {"Twi","tw"},
        {"Uighur, Uyghur","ug"},
        {"Ukrainian","uk"},
        {"Urdu","ur"},
        {"Uzbek","uz"},
        {"Venda","ve"},
        {"Vietnamese","vi"},
        {"Volapük","vo"},
        {"Walloon","wa"},
        {"Welsh","cy"},
        {"Wolof","wo"},
        {"Xhosa","xh"},
        {"Yiddish","yi"},
        {"Yoruba","yo"},
        {"Zhuang, Chuang","za"},
        {"Zulu","zu"}
    };

    
    private final static String[][] iso3166Data = {
        {"Afghanistan", "AF"},
        {"Åland Islands", "AX"},
        {"Albania", "AL"},
        {"Algeria", "DZ"},
        {"American Samoa", "AS"},
        {"Andorra", "AD"},
        {"Angola", "AO"},
        {"Anguilla", "AI"},
        {"Antarctica", "AQ"},
        {"Antigua and Barbuda", "AG"},
        {"Argentina", "AR"},
        {"Armenia", "AM"},
        {"Aruba", "AW"},
        {"Australia", "AU"},
        {"Austria", "AT"},
        {"Azerbaijan", "AZ"},
        {"Bahamas (the)", "BS"},
        {"Bahrain", "BH"},
        {"Bangladesh", "BD"},
        {"Barbados", "BB"},
        {"Belarus", "BY"},
        {"Belgium", "BE"},
        {"Belize", "BZ"},
        {"Benin", "BJ"},
        {"Bermuda", "BM"},
        {"Bhutan", "BT"},
        {"Bolivia (Plurinational State of)", "BO"},
        {"Bonaire", "BQ"},
        {"Sint Eustatius", "BQ"},
        {"Saba", "BQ"},
        {"Bosnia and Herzegovina", "BA"},
        {"Botswana", "BW"},
        {"Bouvet Island", "BV"},
        {"Brazil", "BR"},
        {"British Indian Ocean Territory (the)", "IO"},
        {"Brunei Darussalam", "BN"},
        {"Bulgaria", "BG"},
        {"Burkina Faso", "BF"},
        {"Burundi", "BI"},
        {"Cabo Verde", "CV"},
        {"Cambodia", "KH"},
        {"Cameroon", "CM"},
        {"Canada", "CA"},
        {"Cayman Islands (the)", "KY"},
        {"Central African Republic (the)", "CF"},
        {"Chad", "TD"},
        {"Chile", "CL"},
        {"China", "CN"},
        {"Christmas Island", "CX"},
        {"Cocos (Keeling) Islands (the)", "CC"},
        {"Colombia", "CO"},
        {"Comoros (the)", "KM"},
        {"Congo (the Democratic Republic of the)", "CD"},
        {"Congo (the)", "CG"},
        {"Cook Islands (the)", "CK"},
        {"Costa Rica", "CR"},
        {"Côte d'Ivoire", "CI"},
        {"Croatia", "HR"},
        {"Cuba", "CU"},
        {"Curaçao", "CW"},
        {"Cyprus", "CY"},
        {"Czechia", "CZ"},
        {"Denmark", "DK"},
        {"Djibouti", "DJ"},
        {"Dominica", "DM"},
        {"Dominican Republic (the)", "DO"},
        {"Ecuador", "EC"},
        {"Egypt", "EG"},
        {"El Salvador", "SV"},
        {"Equatorial Guinea", "GQ"},
        {"Eritrea", "ER"},
        {"Estonia", "EE"},
        {"Eswatini", "SZ"},
        {"Ethiopia", "ET"},
        {"Falkland Islands (the) [Malvinas]", "FK"},
        {"Faroe Islands (the)", "FO"},
        {"Fiji", "FJ"},
        {"Finland", "FI"},
        {"France", "FR"},
        {"French Guiana", "GF"},
        {"French Polynesia", "PF"},
        {"French Southern Territories (the)", "TF"},
        {"Gabon", "GA"},
        {"Gambia (the)", "GM"},
        {"Georgia", "GE"},
        {"Germany", "DE"},
        {"Ghana", "GH"},
        {"Gibraltar", "GI"},
        {"Greece", "GR"},
        {"Greenland", "GL"},
        {"Grenada", "GD"},
        {"Guadeloupe", "GP"},
        {"Guam", "GU"},
        {"Guatemala", "GT"},
        {"Guernsey", "GG"},
        {"Guinea", "GN"},
        {"Guinea-Bissau", "GW"},
        {"Guyana", "GY"},
        {"Haiti", "HT"},
        {"Heard Island and McDonald Islands", "HM"},
        {"Holy See (the)", "VA"},
        {"Honduras", "HN"},
        {"Hong Kong", "HK"},
        {"Hungary", "HU"},
        {"Iceland", "IS"},
        {"India", "IN"},
        {"Indonesia", "ID"},
        {"Iran (Islamic Republic of)", "IR"},
        {"Iraq", "IQ"},
        {"Ireland", "IE"},
        {"Isle of Man", "IM"},
        {"Israel", "IL"},
        {"Italy", "IT"},
        {"Jamaica", "JM"},
        {"Japan", "JP"},
        {"Jersey", "JE"},
        {"Jordan", "JO"},
        {"Kazakhstan", "KZ"},
        {"Kenya", "KE"},
        {"Kiribati", "KI"},
        {"Korea (the Democratic People's Republic of)", "KP"},
        {"Korea (the Republic of)", "KR"},
        {"Kuwait", "KW"},
        {"Kyrgyzstan", "KG"},
        {"Lao People's Democratic Republic (the)", "LA"},
        {"Latvia", "LV"},
        {"Lebanon", "LB"},
        {"Lesotho", "LS"},
        {"Liberia", "LR"},
        {"Libya", "LY"},
        {"Liechtenstein", "LI"},
        {"Lithuania", "LT"},
        {"Luxembourg", "LU"},
        {"Macao", "MO"},
        {"North Macedonia", "MK"},
        {"Madagascar", "MG"},
        {"Malawi", "MW"},
        {"Malaysia", "MY"},
        {"Maldives", "MV"},
        {"Mali", "ML"},
        {"Malta", "MT"},
        {"Marshall Islands (the)", "MH"},
        {"Martinique", "MQ"},
        {"Mauritania", "MR"},
        {"Mauritius", "MU"},
        {"Mayotte", "YT"},
        {"Mexico", "MX"},
        {"Micronesia (Federated States of)", "FM"},
        {"Moldova (the Republic of)", "MD"},
        {"Monaco", "MC"},
        {"Mongolia", "MN"},
        {"Montenegro", "ME"},
        {"Montserrat", "MS"},
        {"Morocco", "MA"},
        {"Mozambique", "MZ"},
        {"Myanmar", "MM"},
        {"Namibia", "NA"},
        {"Nauru", "NR"},
        {"Nepal", "NP"},
        {"Netherlands (the)", "NL"},
        {"New Caledonia", "NC"},
        {"New Zealand", "NZ"},
        {"Nicaragua", "NI"},
        {"Niger (the)", "NE"},
        {"Nigeria", "NG"},
        {"Niue", "NU"},
        {"Norfolk Island", "NF"},
        {"Northern Mariana Islands (the)", "MP"},
        {"Norway", "NO"},
        {"Oman", "OM"},
        {"Pakistan", "PK"},
        {"Palau", "PW"},
        {"Palestine, State of", "PS"},
        {"Panama", "PA"},
        {"Papua New Guinea", "PG"},
        {"Paraguay", "PY"},
        {"Peru", "PE"},
        {"Philippines (the)", "PH"},
        {"Pitcairn Islands", "PN"},
        {"Poland", "PL"},
        {"Portugal", "PT"},
        {"Puerto Rico", "PR"},
        {"Qatar", "QA"},
        {"Réunion", "RE"},
        {"Romania", "RO"},
        {"Russian Federation (the)", "RU"},
        {"Rwanda", "RW"},
        {"Saint Barthélemy", "BL"},
        {"Saint Helena", "SH"},
        {"Ascension Island", "SH"},
        {"Tristan da Cunha", "SH"},
        {"Saint Kitts and Nevis", "KN"},
        {"Saint Lucia", "LC"},
        {"Saint Martin (French part)", "MF"},
        {"Saint Pierre and Miquelon", "PM"},
        {"Saint Vincent and the Grenadines", "VC"},
        {"Samoa", "WS"},
        {"San Marino", "SM"},
        {"São Tomé and Príncipe", "ST"},
        {"Saudi Arabia", "SA"},
        {"Senegal", "SN"},
        {"Serbia", "RS"},
        {"Seychelles", "SC"},
        {"Sierra Leone", "SL"},
        {"Singapore", "SG"},
        {"Sint Maarten (Dutch part)", "SX"},
        {"Slovakia", "SK"},
        {"Slovenia", "SI"},
        {"Solomon Islands", "SB"},
        {"Somalia", "SO"},
        {"South Africa", "ZA"},
        {"South Georgia and the South Sandwich Islands", "GS"},
        {"South Sudan", "SS"},
        {"Spain", "ES"},
        {"Sri Lanka", "LK"},
        {"Sudan (the)", "SD"},
        {"Suriname", "SR"},
        {"Svalbard", "SJ"},
        {"Jan Mayen", "SJ"},
        {"Sweden", "SE"},
        {"Switzerland", "CH"},
        {"Syrian Arab Republic (the)", "SY"},
        {"Taiwan (Province of China)", "TW"},
        {"Tajikistan", "TJ"},
        {"Tanzania, the United Republic of", "TZ"},
        {"Thailand", "TH"},
        {"Timor-Leste", "TL"},
        {"Togo", "TG"},
        {"Tokelau", "TK"},
        {"Tonga", "TO"},
        {"Trinidad and Tobago", "TT"},
        {"Tunisia", "TN"},
        {"Turkey", "TR"},
        {"Turkmenistan", "TM"},
        {"Turks and Caicos Islands (the)", "TC"},
        {"Tuvalu", "TV"},
        {"Uganda", "UG"},
        {"Ukraine", "UA"},
        {"United Arab Emirates (the)", "AE"},
        {"United Kingdom of Great Britain and Northern Ireland (the)", "GB"},
        {"United States Minor Outlying Islands (the)", "UM"},
        {"United States of America (the)", "US"},
        {"Uruguay", "UY"},
        {"Uzbekistan", "UZ"},
        {"Vanuatu", "VU"},
        {"Venezuela (Bolivarian Republic of)", "VE"},
        {"Viet Nam", "VN"},
        {"Virgin Islands (British)", "VG"},
        {"Virgin Islands (U.S.)", "VI"},
        {"Wallis and Futuna", "WF"},
        {"Western Sahara Western Sahara", "EH"},
        {"Yemen", "YE"},
        {"Zambia", "ZM"},
        {"Zimbabwe", "ZW"}
    };

    public static String iso639SearchByKey(String key) {
        for (int i = 0; i < iso639Data.length; i++) {
            if ((iso639Data[i][1]).contains(key)) {
                return iso639Data[i][0];
            }
        }
        return null;
    }

    public static String[] iso639SearchByLanguage(String language) {
        String[] result = new String[0];
        for (int i = 0; i < iso639Data.length; i++) {
            if ((iso639Data[i][0]).contains(language)) {
                String[] tmp = new String[result.length+1];
                int j = 0;
                for (; j < result.length; j++) {
                    tmp[j] = result[j];
                }
                tmp[j] = iso639Data[i][1];
                result = tmp;
            }
        }
        return result;
    }

    public static String[] iso3166SearchByKey(String key) {
        String[] result = new String[0];
        for (int i = 0; i < iso3166Data.length; i++) {
            if ((iso3166Data[i][1]).contains(key)) {
                String[] tmp = new String[result.length + 1];
                int j = 0;
                for (; j < result.length; j++) {
                    tmp[j] = result[j];
                }
                tmp[j] = iso3166Data[i][0];
                result = tmp;
            }
        }
        return result;
    }

    public static String[] iso3166SearchByCountry(String country) {
        String[] result = new String[0];
        for (int i = 0; i < iso3166Data.length; i++) {
            if ((iso3166Data[i][0]).contains(country)) {
                String[] tmp = new String[result.length + 1];
                int j = 0;
                for (; j < result.length; j++) {
                    tmp[j] = result[j];
                }
                tmp[j] = iso3166Data[i][1];
                result = tmp;
            }
        }
        return result;
    }
}
